name: Build Ant Java App

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "24"

      - name: Set up Ant
        run: sudo apt-get update && sudo apt-get install -y ant

      - name: Build jar
        run: ant clean jar

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: flghtbookingDemo-jar
          path: dist/flghtbookingDemo.jar

  
