name: Java CI with Ant

on:
 Push:
  branches: ["master"]
 pull_request:
  branches: ["master"]

 jobs:
  build:
   runs-on: ubuntu-latest

   steps:
   -name: Checkout code
    uses: actions/checkout@v4

   -name: Set up JDK
    uses: actions/setup-java@v4
    with:
     java-version: '17' # Change this to match your projects version
     distribution: 'termurin

  -name: Build with Ant
   run: ant -nionput -buildfile build.xml
  
